PREFIX : <http://example.org/> 
PREFIX foaf:       <http://xmlns.com/foaf/0.1/>
SELECT * WHERE {
SERVICE <http://localhost:3031/data2/sparql> { {{?Y ?Z ?T} UNION {:a ?Y :b} FILTER (:a = ?Y) } }
 
 SERVICE <http://localhost:3031/data1/sparql> { :a foaf:knows ?Q . } 
}
