# from MGI to HGCN: high selectivity since we fix the resource URI and low selectivity from HGCN
select * where {
  service<http://localhost:8080/rdf4j-server/repositories/mgi> {
    <http://bio2rdf.org/mgi:1915545> ?p ?join .
}

  service<http://localhost:8080/rdf4j-server/repositories/hgnc> {
    ?join <http://bio2rdf.org/hgnc_vocabulary:status> "Approved" .
  }
}